name: hum_1618
description: A new Flutter project.


version: 1.0.0+1

environment:


  sdk: ">=2.1.0 <3.0.0"
  # Dart SDK Version
  # Note - If recieving Dart version error,
  # refrerence ->  https://dartcode.org/docs/quickly-switching-between-sdk-versions/

dependencies:
  flutter:
    sdk: flutter
    
  async_loader:

  # FireBase Dependcies
  firebase_storage:
  firebase_core: ^0.3.1+1
  firebase_auth: ^0.8.3
  cloud_firestore:
  google_sign_in: ^4.0.1+1
  
  # Camera Depends.
  image_picker: ^0.5.4
  camera: 
  path_provider: ^0.5.0
  video_player: ^0.10.0
  
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  # Picutres Assests 
  assets:
  - assets/
  